import {
  Accessibility,
  Baby,
  Banknote,
  Bath,
  Beer,
  Building,
  BusFront,
  Castle,
  Church,
  Coffee,
  Film,
  Footprints,
  GraduationCap,
  Hotel,
  Landmark,
  Library,
  MapPin,
  Pill,
  ShoppingBag,
  Star,
  Stethoscope,
  Store,
  Theater,
  TrainFront,
  Trees,
  Utensils,
  type LucideIcon,
} from 'lucide-react'
import type { CategoryKey, PresetId } from './core/types'

export const PRESET_ICON: Record<PresetId, LucideIcon> = {
  wheelchair: Accessibility,
  stroller: Baby,
  walking: Footprints,
}

export const CATEGORY_ICON: Record<CategoryKey, LucideIcon> = {
  museum: Landmark,
  church: Church,
  theatre: Theater,
  cinema: Film,
  monument: Castle,
  attraction: Star,
  restaurant: Utensils,
  cafe: Coffee,
  bar: Beer,
  hotel: Hotel,
  toilets: Bath,
  shop: Store,
  mall: ShoppingBag,
  pharmacy: Pill,
  health: Stethoscope,
  office: Building,
  library: Library,
  station: TrainFront,
  stop: BusFront,
  bank: Banknote,
  education: GraduationCap,
  park: Trees,
  other: MapPin,
}
