import type { BBox } from '../core/geo.ts'
import type { LngLat, Localized } from '../core/types.ts'

/** A public dataset we plan to (or already) read. Documented per city so the data flow is transparent. */
export type DatasetInfo = {
  name: Localized
  publisher: string
  url: string
  format: string
  license: string
  /** How often the publisher updates it and how often we fetch it. */
  refresh: string
  status: 'used' | 'planned'
}

/**
 * Everything that is specific to one city. Adding a city = adding one of these files
 * and running `npm run data:fetch -- <city>`; the rest of the app is city-agnostic.
 */
export type CityConfig = {
  id: string
  name: Localized
  center: LngLat
  /** Area loaded on start, [south, west, north, east]. */
  bbox: BBox
  /** Prebuilt copy of the places for when OpenStreetMap is unavailable (generated by the data pipeline). */
  snapshotUrl: string
  /** Prebuilt copy of the footway network (optional, generated by the data pipeline). */
  networkSnapshotUrl?: string
  /** Area of the saved footway network: `bbox` and a margin, so routes between its places work without the live servers. */
  networkBbox?: BBox
  /** Public transport stops published by the city (optional): the live layer and its nightly copy. */
  stops?: { serviceUrl: string; snapshotUrl: string }
  /** Example routes for the demo and onboarding. */
  exampleRoutes: { from: string; to: string }[]
  datasets: DatasetInfo[]
}
